"""Contractual coupon schedule generation for fixed-to-reset AT1 instruments.

Simplifications (see ``docs/methodology.md``)
---------------------------------------------
- Coupon dates are generated by adding whole calendar months to the issue
  date. There is no business-day adjustment or holiday calendar.
- ``ACT_ACT`` is approximated as actual days / 365.25.
- The reset benchmark rate is assumed constant after the first reset, so all
  post-reset coupons pay ``assumed benchmark + contractual margin``.
- The terminal call date must fall exactly on the coupon schedule; misaligned
  dates raise :class:`ScheduleError` rather than generating a stub period.
"""

from __future__ import annotations

import calendar
from datetime import date
from math import isfinite

import pandas as pd

from at1radar.dates import add_months
from at1radar.domain.instruments import AT1Instrument, DayCount

# Re-export for callers that historically imported from this module.
__all__ = [
    "SCHEDULE_COLUMNS",
    "ScheduleError",
    "add_months",
    "generate_coupon_schedule",
    "year_fraction",
]

SCHEDULE_COLUMNS = [
    "payment_date",
    "period_start",
    "period_end",
    "year_fraction",
    "coupon_rate",
    "coupon_cashflow",
    "principal_cashflow",
    "total_cashflow",
    "is_post_reset",
]


class ScheduleError(ValueError):
    """Raised when a coupon schedule cannot be generated."""


def year_fraction(start: date, end: date, day_count: DayCount) -> float:
    """Year fraction between two dates under a (simplified) day-count convention.

    - ``ACT_365``: actual days / 365.
    - ``ACT_ACT``: approximated as actual days / 365.25 (documented simplification;
      the full ISDA ACT/ACT rule is out of scope for this prototype).
    - ``THIRTY_360``: US 30/360 rule with day-of-month capping.
    """
    if end < start:
        raise ValueError(f"end date {end} is before start date {start}")
    if day_count is DayCount.ACT_365:
        return (end - start).days / 365.0
    if day_count is DayCount.ACT_ACT:
        return (end - start).days / 365.25
    # THIRTY_360 (US convention). The order matters for February month-ends.
    d1 = start.day
    d2 = end.day
    start_is_last_of_february = start.month == 2 and d1 == calendar.monthrange(start.year, 2)[1]
    end_is_last_of_february = end.month == 2 and d2 == calendar.monthrange(end.year, 2)[1]
    if start_is_last_of_february:
        if end_is_last_of_february:
            d2 = 30
        d1 = 30
    if d2 == 31 and d1 >= 30:
        d2 = 30
    if d1 == 31:
        d1 = 30
    days_360 = (end.year - start.year) * 360 + (end.month - start.month) * 30 + (d2 - d1)
    return days_360 / 360.0


def generate_coupon_schedule(
    instrument: AT1Instrument,
    valuation_date: date,
    terminal_call_date: date,
    assumed_reset_benchmark_rate: float,
) -> pd.DataFrame:
    """Generate the contractual coupon schedule up to a terminal call date.

    Parameters
    ----------
    instrument:
        The AT1 instrument whose terms drive the schedule.
    valuation_date:
        Cash flows on or before this date are excluded.
    terminal_call_date:
        The date on which the instrument is assumed to be redeemed at par.
        Must lie exactly on the coupon schedule.
    assumed_reset_benchmark_rate:
        Decimal benchmark rate assumed to prevail (constant) after the first
        reset. Post-reset coupons pay this rate plus the contractual margin.

    Returns
    -------
    pandas.DataFrame
        One row per remaining payment with the columns in
        :data:`SCHEDULE_COLUMNS`. The final row repays the notional.
    """
    if terminal_call_date <= valuation_date:
        raise ScheduleError(
            f"terminal_call_date ({terminal_call_date}) must be after "
            f"valuation_date ({valuation_date})"
        )
    if terminal_call_date < instrument.first_call_date:
        raise ScheduleError(
            f"terminal_call_date ({terminal_call_date}) is before the first call date "
            f"({instrument.first_call_date})"
        )
    if not isfinite(assumed_reset_benchmark_rate):
        raise ScheduleError(
            f"assumed_reset_benchmark_rate must be finite, got {assumed_reset_benchmark_rate}"
        )

    step = instrument.coupon_frequency.months_per_period
    period_ends: list[date] = []
    k = 1
    while (period_end := add_months(instrument.issue_date, k * step)) <= terminal_call_date:
        period_ends.append(period_end)
        k += 1
    if not period_ends or period_ends[-1] != terminal_call_date:
        raise ScheduleError(
            f"terminal_call_date ({terminal_call_date}) does not fall on the "
            f"{instrument.coupon_frequency.value} coupon schedule anchored at the issue date "
            f"({instrument.issue_date})"
        )

    reset_rate = assumed_reset_benchmark_rate + instrument.reset_margin
    if not isfinite(reset_rate):
        raise ScheduleError(f"post-reset coupon rate must be finite, got {reset_rate}")
    rows: list[dict[str, object]] = []
    for i, period_end in enumerate(period_ends):
        period_start = instrument.issue_date if i == 0 else period_ends[i - 1]
        if period_end <= valuation_date:
            continue
        # The coupon resets on the first call date, so periods *starting* on or
        # after that date pay the reset rate.
        is_post_reset = period_start >= instrument.first_call_date
        coupon_rate = reset_rate if is_post_reset else instrument.current_coupon_rate
        fraction = year_fraction(period_start, period_end, instrument.day_count)
        coupon_cashflow = instrument.notional * coupon_rate * fraction
        principal_cashflow = instrument.notional if period_end == terminal_call_date else 0.0
        rows.append(
            {
                "payment_date": period_end,
                "period_start": period_start,
                "period_end": period_end,
                "year_fraction": fraction,
                "coupon_rate": coupon_rate,
                "coupon_cashflow": coupon_cashflow,
                "principal_cashflow": principal_cashflow,
                "total_cashflow": coupon_cashflow + principal_cashflow,
                "is_post_reset": is_post_reset,
            }
        )
    return pd.DataFrame(rows, columns=SCHEDULE_COLUMNS)
